# Site settings
title: Andrew Seidl
email: hi@andrewseidl.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewseidl.com" # the base hostname & protocol for your site
twitter_username: andrew_seidl
github_username:  andrewseidl
linkedin_username: andrewseidl
googleplus_username: +AndrewSeidlcom
hackernews_username: aseidl

# Build settings
markdown: kramdown
